### ISSUE TITLE
Config import script doesn't work with drush 11

### ISSUE THREAD

**Issue by larowlan** [govCMS/scaffold-tooling#241]
## Problem statement
composer.json lets you install drush 11, but the script for running config import passes an additional 'sync' argument to `drush config-import` which isn't supported in drush 11.

## Proposed resolution
Determine if this is still needed or if sync is the default in versions of drush < 11

**Comment by stooit** [comment]
Thanks @larowlan. Fixed in https://github.com/govCMS/scaffold-tooling/commit/84268bdc58d6a4b067dfdb61f26ee9f54ec3efc2 (`10.x-develop` branch).

Note D10 support in all tooling repos will remain WIP until the distribution itself has a D10 preview release ready to go, however vanilla D10 support is available in the scaffold in [this PR](https://github.com/govCMS/scaffold/pull/64). When coupled with the `10.x-develop` branch of scaffold-tooling everything is working as expected, except the validations for mandatory/expected modules (which depend on the distribution).

**Comment by larowlan** [comment]
Hi drush 11 supports d9 too, fwiw

**Comment by stooit** [comment]
Yeah, assumed you were talking D10 here -- have raised PR https://github.com/govCMS/scaffold-tooling/pull/242 for inclusion in an upcoming release.
