### ISSUE TITLE
Support Drupal 9

### ISSUE THREAD

**Issue by larowlan** [govCMS/scaffold-tooling#58]
I'm working on a paas project and was looking to retain the govcms/scaffold-tooling entry in our composer.json

But its not Drupal 9 compatible because of the following:

- clamav - no D9 version (see https://www.drupal.org/project/clamav/issues/3131448)
- chosen_lib hard-pinned to 2.6.0 (relaxing this to ~2 would allow Drupal 9)
- drush 9 (suggest make this ~9 || ~10)
- stage_file_proxy pinned to an alpha version (relax this to ~1)
- fast_404 (see #57 and https://www.drupal.org/project/fast_404/issues/3042976)
- redis hard-pinned to 1.1.0 (relaxing this to ~1 would allow Drupal 9)
- drupal-console requires symfony/console 3, but core require 4+

**Comment by simesy** [comment]
I agree with loosening constraints per best-practice Composer.

**One to note:** `chosen_lib` being hard-pinned got around a dependency resolution issue, and it might be possible to just remove it. (From memory this was because chosen module has a dependency on a sub-module, instead of the typical pattern where sub-modules have dependencies on the main module. https://www.drupal.org/project/chosen/issues/3054793#comment-13231195)

**Comment by pandaskii** [comment]
Thanks, @larowlan for the list

We are also tracking this issue internally.

**Comment by pandaskii** [comment]
Using drupal_check or other tools to check these modules are also needed so that we can have a picture of D9.

I am running it locally and will post it once I finished

**Comment by larowlan** [comment]
`composer why-not -t drupal/core:~9` is how I got this list

**Comment by pandaskii** [comment]
@larowlan thanks for the tips

**Comment by stooit** [comment]
A `9.x` branch now exists which is D9 compatible, as indicated it is missing some of the dependencies (fast_404, clamav) that do not have 9.x release on Drupal.org at present

Patched versions of these modules are _temporarily_ included in the `9.x` branch of govcms8lagoon: https://github.com/govCMS/govcms8lagoon/tree/9.x/modules, which also includes WIP GovCMS9 distribution for pre-release testing.
